### ISSUE TITLE
Test failures when standard plan instance is used

### ISSUE THREAD

**Issue by yumaoka** [IBM-Cloud/gp-js-client#110]
When testing gp-js-client with a globalization pipeline service instance using the standard plan (not professional plan), some test cases are failing because of feature restriction.

```
  1) gaasClient.setup instance lon6a2948ae53a91867a13c5b186f2b2b9ce6eec788 Should let us get service instance info:
     AssertionError: expected undefined to be a boolean
      at test\client-test.js:326:51
      at p.then.d (lib\utils.js:262:16)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Above test cases expects htServiceEnabled to be true, while it's false if the GP instance used for testing is "standard".

Then, other test cases - testing APIs only supported with "professional" plan are failing, e.g.

```
  5) GP-HPE tr() and trs() api test Should let us call trs() and have an empty list:
     Error: done() invoked with non-Error: Not a REST group:translation_request
      at test\tr-test.js:170:23
      at p.then.catch.e (lib\utils.js:263:17)
      at <anonymous>

  6) GP-HPE: Requesting our first TR Should request the first TR:
     Error: done() invoked with non-Error: Not a REST group:translation_request
      at cb (test\tr-test.js:258:25)
      at p.then.catch.e (lib\utils.js:263:17)
      at <anonymous>
...
```

The test code should skip these test cases when human translation feature is disabled.

**Comment by srl295** [comment]
One problem is that the easiest way to do test disabling has to be done synchronously, outside of the test mechanism. Could I have an env var to say that the standard plan is expected?
